version: "3.7"
services:
  db:
    image: postgres:12
    container_name: babish-ibdb
    ports:
      - "54320:5432"
    volumes:
      - ./ibdb/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    #   - ./tmp/pgdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes: ["./ibdb:/app/ibdb", "./vendor:/app/vendor"]
    image: babish-ibdb-api:latest
    container_name: babish-ibdb-api
    ports:
      - "5000:5000"
    depends_on:
      - db